/**
 * This js file contains all functions related to analyzing a user's profile
 */

 const {spotify} = require('./spotify');

 const defaultGenres = [
    "acoustic",
    "afrobeat",
    "alt-rock",
    "alternative",
    "ambient",
    "anime",
    "black-metal",
    "bluegrass",
    "blues",
    "bossanova",
    "brazil",
    "breakbeat",
    "british",
    "cantopop",
    "chicago-house",
    "children",
    "chill",
    "classical",
    "club",
    "comedy",
    "country",
    "dance",
    "dancehall",
    "death-metal",
    "deep-house",
    "detroit-techno",
    "disco",
    "disney",
    "drum-and-bass",
    "dub",
    "dubstep",
    "edm",
    "electro",
    "electronic",
    "emo",
    "folk",
    "forro",
    "french",
    "funk",
    "garage",
    "german",
    "gospel",
    "goth",
    "grindcore",
    "groove",
    "grunge",
    "guitar",
    "happy",
    "hard-rock",
    "hardcore",
    "hardstyle",
    "heavy-metal",
    "hip-hop",
    "holidays",
    "honky-tonk",
    "house",
    "idm",
    "indian",
    "indie",
    "indie-pop",
    "industrial",
    "iranian",
    "j-dance",
    "j-idol",
    "j-pop",
    "j-rock",
    "jazz",
    "k-pop",
    "kids",
    "latin",
    "latino",
    "malay",
    "mandopop",
    "metal",
    "metal-misc",
    "metalcore",
    "minimal-techno",
    "movies",
    "mpb",
    "new-age",
    "new-release",
    "opera",
    "pagode",
    "party",
    "philippines-opm",
    "piano",
    "pop",
    "pop-film",
    "post-dubstep",
    "power-pop",
    "progressive-house",
    "psych-rock",
    "punk",
    "punk-rock",
    "r-n-b",
    "rainy-day",
    "reggae",
    "reggaeton",
    "road-trip",
    "rock",
    "rock-n-roll",
    "rockabilly",
    "romance",
    "sad",
    "salsa",
    "samba",
    "sertanejo",
    "show-tunes",
    "singer-songwriter",
    "ska",
    "sleep",
    "songwriter",
    "soul",
    "soundtracks",
    "spanish",
    "study",
    "summer",
    "swedish",
    "synth-pop",
    "tango",
    "techno",
    "trance",
    "trip-hop",
    "turkish",
    "work-out",
    "world-music"
  ];

const myTopGenres = {
    'dance pop': 14,      
    edm: 13,
    electropop: 32,       
    pop: 47,
    'pop dance': 12,      
    'tropical house': 13, 
    'k-pop': 2,
    'k-pop girl group': 2,
    'pop rap': 7,
    indietronica: 2,      
    'modern rock': 11,
    'pop rock': 7,
    'post-teen pop': 17,
    'electro house': 7,
    'electronic trap': 2,
    'future bass': 4,
    'pop edm': 9,
    'vapor twitch': 4,
    'alt z': 28,
    'chill r&b': 3,
    'alternative pop rock': 1,
    'alternative hip hop': 1,
    'anthem worship': 6,
    ccm: 8,
    'christian alternative rock': 4,
    'christian music': 7,
    'world worship': 6,
    worship: 6,
    'indie cafe pop': 14,
    indiecoustica: 5,
    'neo mellow': 1,
    'indie pop rap': 1,
    metropopolis: 5,
    'norwegian pop': 1,
    etherpop: 1,
    'indie poptimism': 22,
    'russian ccm': 1,
    'australian hip hop': 1,
    rock: 4,
    'indie electropop': 10,
    'indie pop': 14,
    'la pop': 7,
    'vapor soul': 5,
    'bedroom pop': 2,
    bubblegrunge: 1,
    'norwegian indie': 2,
    'canadian pop': 5,
    'candy pop': 1,
    'uk pop': 4,
    'bass trap': 3,
    'boston hip hop': 1,
    'indie rock': 1,
    'modern alternative rock': 8,
    'swedish electropop': 1,
    'melodic dubstep': 1,
    'j-pop': 1,
    'j-poprock': 1,
    'j-rock': 1,
    'japanese emo': 1,
    'visual kei': 1,
    'viral pop': 1,
    'gaming edm': 2,
    traprun: 1,
    chillstep: 1,
    wave: 1,
    'christian pop': 2,
    'ambient folk': 1,
    'indie folk': 1,
    'denton tx indie': 1,
    'diy emo': 1,
    hopebeat: 4,
    'la indie': 1,
    'j-indie': 1,
    'minnesota hip hop': 1,
    'chicago rap': 1,
    'melodic rap': 1,
    'shimmer pop': 1,
    'stomp and holler': 2,
    'nyc pop': 1,
    'chill pop': 2,
    'social media pop': 2,
    'singaporean electronic': 1,
    'singaporean pop': 1,
    brostep: 1,
    'progressive electro house': 2,
    'folk-pop': 1,
    'irish pop': 1,
    'alternative emo': 2,
    'indie garage rock': 1,
    'deep euro house': 1,
    'german dance': 1,
    'indy indie': 1,
    'alternative r&b': 1,
    house: 1,
    'progressive house': 2,
    'uk dance': 1,
    'modern indie pop': 1,
    'art pop': 2,
    'canadian electropop': 1,
    'escape room': 1,
    'alternative ccm': 1,
    'ambient worship': 1,
    'nz pop': 1
  }

const brockTopGenres = {
    'ambient worship': 2,
    ccm: 9,
    'christian music': 6,
    'deep ccm': 2,       
    'world worship': 8,  
    worship: 7,
    'dfw rap': 1,        
    'melodic rap': 3,    
    rap: 15,
    'neo mellow': 3,     
    pop: 26,
    'pop rock': 7,       
    'singer-songwriter': 1,
    'canadian hip hop': 1,
    'canadian pop': 4,
    'hip hop': 14,
    'pop rap': 9,
    'toronto rap': 1,
    'alt z': 2,
    electropop: 4,
    hopebeat: 1,
    'indie cafe pop': 5,
    'indie pop': 2,
    'indie poptimism': 2,
    'modern alternative rock': 4,
    'modern rock': 8,
    'anthem worship': 5,
    'acoustic pop': 2,
    indiecoustica: 2,
    'lds youth': 1,
    'piano rock': 2,
    'chamber pop': 1,
    dreamo: 1,
    'nu gaze': 1,
    rock: 4,
    'russian ccm': 1,
    'christian alternative rock': 2,
    'folk-pop': 2,
    'stomp and holler': 2,
    'post-teen pop': 10,
    'uk pop': 1,
    'christian pop': 1,
    'emo rap': 1,
    'miami hip hop': 2,
    'conscious hip hop': 4,
    'dmv rap': 2,
    'alternative r&b': 6,
    'viral pop': 3,
    'canadian contemporary r&b': 2,
    'r&b': 5,
    'permanent wave': 1,
    'kentucky indie': 1,
    'kentucky roots': 1,
    'outlaw country': 4,
    'atl hip hop': 1,
    trap: 4,
    'contemporary country': 12,
    'texas country': 9,
    'chicago rap': 2,
    'deep talent show': 1,
    'red dirt': 4,
    'irish pop': 2,
    'shiver pop': 1,
    'boy band': 2,
    'north carolina hip hop': 1,
    'lgbtq+ hip hop': 1,
    'neo soul': 1,
    'dance pop': 5,
    'la pop': 1,
    'hawaiian hip hop': 1,
    'indie rock': 1,
    'la indie': 1,
    'chill r&b': 2,
    'indie r&b': 2,
    'indie soul': 1,
    'ohio hip hop': 1,
    country: 9,
    'country road': 9,
    'country dawn': 1,
    'oklahoma country': 1,
    'christian hip hop': 1,
    'mellow gold': 1,
    'rock drums': 1,
    'soft rock': 1,
    'meme rap': 1,
    'underground hip hop': 1,
    'vapor trap': 1,
    'modern country rock': 3,
    'arkansas country': 1,
    'country pop': 2,
    'pop r&b': 1,
    'detroit hip hop': 1,
    'southern hip hop': 2,
    'modern indie pop': 1,
    'ambient folk': 1,
    'indie folk': 2,
    'album rock': 1,
    'classic rock': 1,
    'country rock': 2,
    'roots rock': 1,
    'southern rock': 1,
    'swamp rock': 1,
    'austin americana': 1,
    austindie: 1,
    'deep new americana': 1,
    'new americana': 1,
    redneck: 1,
    'baroque pop': 1,
    emo: 1,
    'pittsburgh rap': 1,
    'alternative pop rock': 1,
    'neon pop punk': 1,
    'pop emo': 1,
    'pop punk': 1,
    'indie anthem-folk': 1,
    'neo-traditional country': 1,
    'west coast rap': 1
  }

//Artist rankings start from ALL TIME -> Med -> short. 0 - 150
const usertopArtists = async (access_token) => {
    const long = await spotify.getUserTopArtists(access_token, "long_term");
    const medium = await spotify.getUserTopArtists(access_token, "medium_term");
    const short = await spotify.getUserTopArtists(access_token, "short_term");

    const artists = long.items.concat(medium.items, short.items);
    
    const artistIds = [];
    let genresMap = {};
    artists.forEach(artist => {
        const id = artist.id;
        const genres = artist.genres;
        
        //Add artist to artistsId array if artist doesn't already exist
        if(!artistIds.includes(id)) {
            artistIds.push(id);
            genres.forEach(genre => {
                if(genre in genresMap){
                    genresMap[genre] += 1;
                }else{
                    genresMap[genre] = 1;
                }
            })
        }
    });
    top100Artists = artistIds.slice(0,100);
    console.log(top100Artists.length);
    console.log(genresMap);
};

//usertopArtists("BQDE6DFFk_lx700EZq-o7-5c6ehSn54OyYyi37oxLEnrixNotN-IHF-rTFdxLQXstPYyAFnBZUyl-rZsXFQ8Apu_I1uUCur4Ud7Ntt9DJQbiNSf4UsAzBqrkF30vlhewscjolgCFciz75JcrelhP4VRJ0aYsHoUS5Ch5Adamnsrvi10rCJj0KeI2gUy4NO3YOQI")


const userTopGenres = () => {
    const myGenres = extractNicheGenres(myTopGenres);
    const brockGenres = extractNicheGenres(brockTopGenres);
    const commonNicheGenresArray = myGenres.filter(myGenre => brockGenres.includes(myGenre));
}

const extractNicheGenres = (userGenres) => {
    const userGenresArray = Object.keys(userGenres);
    const nicheGenres = userGenresArray.filter(userGenre => !defaultGenres.includes(userGenre));
    return nicheGenres;
}

userTopGenres();